### ISSUE TITLE
Liquid Exception: Failed to get header. in _posts/2000-01-05-usage.md

### ISSUE THREAD

**Issue by jdoliner** [t413/SinglePaged#11]
I get this when I run `jekyll serve` I'm using version 2.5.2 of Jekyll which I think is the latest.

**Comment by jdoliner** [comment]
Alright this is definitely not a SinglePaged problem. I get this after running `jekyll new` as well.

**Comment by jdoliner** [comment]
However if someone does happen to know the answer to this I'd still love to know.

**Comment by t413** [comment]
It sounds specific to your setup. If you've got a repository you can point me to I'll check it out.

**Comment by jdoliner** [comment]
Yeah it's definitely specific to my setup. I'm not totally sure how I'd replicate it for you since I'm not really sure which parts of my config are responsible for this. 

It all worked out though. I wound up just using https://github.com/grahamc/docker-jekyll which works great. So anyone who finds themselves in a similar problem this would be the thing to do.
