### ISSUE TITLE
Custom font Raleway not used

### ISSUE THREAD

**Issue by TheE** [t413/SinglePaged#16]
A small typo in [line 55](https://github.com/t413/SinglePaged/blob/gh-pages/_includes/css/base.css#L55) of the `base.css` prevents usage of the Raleway font (at least on Firefox) because a comma is missing between `"Raleway"` and `"HelveticaNeue-Light"`.

**Comment by t413** [comment]
Great catch, I'll fix it right away! Thanks

**Comment by jemshit** [comment]
exactly @TheE  :+1:

**Comment by t413** [comment]
Fixed this a while ago, forgot to close! Thanks again.
