### ISSUE TITLE
Quotes are ugly

### ISSUE THREAD

**Issue by NicolasCARPi** [t413/SinglePaged#20]
Hello,

First thanks for this theme, it is quite cool :)

I just want to say that if you use a blockquote like this : 

> This is a quote.

It will be a bit ugly with your theme. Please have a look, I'm sure it's trivial to fix the css for that :)

Regards,
~Nico

**Comment by lyndell** [comment]
I think the backquotes need to be more prominent.

**Comment by NicolasCARPi** [comment]
Closing as this repo is not maintained anymore.
