### ISSUE TITLE
New example page + Feedback

### ISSUE THREAD

**Issue by sils** [t413/SinglePaged#25]
Hi,

we've just built a website (in no time) for our open source project using your template: http://coala-analyzer.org/ , the source is hosted at https://github.com/coala-analyzer/website - in case you want to add that to your example list.

The design is just awesome! A hint about how the icons work would be appreciated but maybe that's just me not knowing Jekyll and I figured it out after all.

Many thanks for providing this!

**Comment by t413** [comment]
Your site looks great, I've added it to the examples! I'll look at the readme section on the icons and see what I can clarify.
