### ISSUE TITLE
Thanks to this awesome theme!

### ISSUE THREAD

**Issue by billryan** [t413/SinglePaged#3]
Take it easy. :) Thanks to your awesome SinglePaged theme. I built my [homepage](http://www.billryan.me) yesterday and added comments section with [Disqus](https://disqus.com/).

**Comment by t413** [comment]
Thanks! It looks great! Nice and stylish, you really made it your own.

If you want some help making your Home section picture blend into the background let me know, it's an easy fix.

**Comment by billryan** [comment]
It will be great if the picture can blend into the background. Change the background color would be helpful. Any other suggestions?

**Comment by t413** [comment]
Here, I've redone it as a transparent PNG with some great photoshop voodoo:

[![avatar-round](https://cloud.githubusercontent.com/assets/326829/4743436/e29aa516-5a27-11e4-897d-13f8e6ee0cab.png)](https://cloud.githubusercontent.com/assets/326829/4743436/e29aa516-5a27-11e4-897d-13f8e6ee0cab.png)

It's actually a far smaller image file too! I used photoshop to cut out the picture from the old one, content-aware fill more background in, created a new 45px-rounded rectangle layer mask, add a 2px stroke using the color from the first section on your site, saved it and extra-compressed it with [TinyPng](http://tinypng.com). Now it'll look great on any background color.

**Comment by t413** [comment]
Actually use [this](https://cloud.githubusercontent.com/assets/326829/4743550/05ebeef2-5a29-11e4-8e08-5ca6caf3b64c.png) one instead. There's no odd border blip (noticed it too late).

**Comment by billryan** [comment]
It looks awesome! Thank you for your generous help!
