### ISSUE TITLE
Output broken wit Jekyll 3.0.0 and 3.0.1

### ISSUE THREAD

**Issue by weinzierl** [t413/SinglePaged#35]
With Jekyll 3.0.0 and 3.0.1 only the post with the highest date is rendered into index.html. Moreover the content of index.html is a simple Markdown translation of the post, the template is not considered apparently. I can confirm that it works properly with Jekyll 2.5.3. I'm quite confident that it works with Jekyll 2.4.0, because that is the version I think I had before the upgrade to 3.0.0.

Reproduce:

``` shell
$ jekyll --version
jekyll 3.0.0
jekyll serve -w
```

Visit http://localhost:4000/, only last post is shown, plain and ugly, with no CSS.

``` shell
$ gem install jekyll -v '2.5.3'
$ gem uninstall jekyll 
```

Select version 3.0.0.

``` shell
$ jekyll --version
jekyll 2.5.3
jekyll serve -w
```

Visit http://localhost:4000/, all's right with the world.

---

I suspect the reason could be a change in the behavior of Permalinks introduced in Jekyll 2, which became effective only in version 3, see [Upgrading from 0.x to 2.x - Absolute PermalinksPermalink](http://jekyllrb.com/docs/upgrading/0-to-2/#absolute-permalinks).

**Comment by lyndell** [comment]
Had the same problem. Forced the version with a Gemfile:

```
source "https://rubygems.org"

gem 'jekyll', '2.5.3'
```

`bundle check` and now the theme works as expected.

**Comment by koppor** [comment]
This is really important as [GitHub switched to Jekyll 3.0](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0).

**Comment by NicolasCARPi** [comment]
Yeah, I have the same problem here.

**Comment by NicolasCARPi** [comment]
@weinzierl You're probably right about the permalinks because commenting the permalink line in config gives you an almost fully functionning page.

If we can't figure out a solution (and staying with 2.x jekyll isn't one), we'll have to switch to another layout because the author of this one seems dead, so I don't believe it'll be fixed.

**Comment by NicolasCARPi** [comment]
If you put : 

`permalink : /:year`

It seems to solve the issue.

**Comment by koppor** [comment]
PR #37 solves the issue.

**Comment by gregology** [comment]
:+1:  to @NicolasCARPi's solution of adding `permalink : /:year` to _config.yml. Also update `highlighter: rouge` if you're hosting on Github pages to stop it complaining.

**Comment by koppor** [comment]
The only issue is that pages with the same title get the same html file, even if one of them is a post and not a direct page. For instance, I have a blog post 2015-10-02_dontations.md and an html file `dontations.html`. With Jekyll 2.x, it was `/#dontations` for the former and `/dontations` (AFAIK redirected to `/dontations/`) for the latter. Now, all these URLs point to the former content and the  content for `dontations.html` is not generated.

**Comment by jemshit** [comment]
@t413  i guess that pull request is still not merged

**Comment by sils** [comment]
We cherrypicked https://github.com/CjS77/SinglePaged/commit/8ab4a4eaa09639d7a352151e3473c7b4fa8c6d4d and it worked since this caused downtime of our website.

**Comment by renewooller** [comment]
I've been having this issue also. But I was curious as to have the single paged site itself is still running eg http://t413.com/SinglePaged/. So I cloned it with a fresh project. http://renewooller.github.io/ Which is displaying the same problem. I guess that it is running of t413's own server somewhere.  I can see that other people have 'fixed' it by using html in their markdown. But then what's the point of markdown? Anyone found a real fix?

**Comment by koppor** [comment]
#37 is the real fix. Please use that fork.

The reason that http://t413.com/SinglePaged/ still serves perfectly might be that the site was not regenerated. The issues with Jekyll and this theme arise only if one generated the page after deployment of Jekyll 3.x on GitHub. GitHub did not regenerate all user pages.

**Comment by t413** [comment]
Hey everybody sorry for the slow movement on this– but output is now fully working on Jekyll 3. Let me know if anyone still has any problems!

**Comment by DavidBurela** [comment]
I'm having this exact issue.  Jekyll 3.4.3

I do a git clone of this repo, and it works fine. But when I run the rest of the commands `git checkout publish && git branch -m master && git push -u origin master && git branch -D gh-pages` then I get this issue and need to manually update my `_config.yml` file and enter the 2 lines.

I'm guessing that the publish branch also needs this fix brought in, so that anyone forking for their own site doesn't come up against the same issue.
