### ISSUE TITLE
Theme does not work online as a project site while renders correctly locally

### ISSUE THREAD

**Issue by vicrucann** [t413/SinglePaged#40]
I'm trying to set up **SinglePaged** theme for one of my github projects. I already have my personal site set up using another Jekyll theme (So-Simple). So, lets assume my personal site runs on `UserName.github.io`. 

For a project site, I created `gh-pages` branch for my github project repository and used SinglePaged files to set up the content of my page. The address of the site would be something like `UserName.github.io/ProjectName`.

When I run `bundle exec jekyll serve` on my machine, the site is built correctly locally. However, when I check how it looks online, all I see is a plain content of the last "post" without any text formatting.

I'm new in Jekyll and web development, but I did little bit of research and found this situation can happen when a certain variable `baseurl` is not set (correctly) for a project site. I do not see `baseurl` variable at the `_config.yml` of **SinglePaged**. 

So my question is: how do I fix this situation? Assuming I add the `baseurl` variable, what files and how do I need to edit them so that they take the `baseurl` into account? Or do I not use **SinglePaged** theme correctly and it is supposed to work without `baseurl`? For reference, I tried some other theme where it is possible to specify the `baseurl` and it rendered correctly online; so from this experience I feel like it is about missing `baseurl`.

I really would like to use **SinglePaged** for my project, so would appreciate any hints in what direction to move.

**Comment by thacoon** [comment]
Hi,

it should render correctly if you use the fork of [CjS77](https://github.com/CjS77).
A link to his fork is [here.](https://github.com/CjS77/SinglePaged)

**Comment by vicrucann** [comment]
Thanks for answering, however I already used another fork ( [htacg](https://github.com/htacg/htacg.github.io) ), and then had to modify it to reset the font and other settings to default values, as I liked them more. Using `baseurl` indeed solved the problem in my case.
