### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [t413/SinglePaged#6]
First, thanks for building this fabulous theme!

Second, would you mind adding a `LICENSE` file? Without one it's technically "All Rights Reserved." Check out http://choosealicense.com/ if you need help picking or just want a quick place to copy/paste a license from. :smile: 

Thanks!

**Comment by t413** [comment]
Fixed with 35c0785d04a9070fb08f57dd0eed59ee9947c457 -- I added the MIT License. Thanks!
